Feature/logger winston 로그 추가
f-lab-edu/dogspot-api-server pull request #7
Opened 2024-06-29 14:39 UTC by wngh4628

로깅 및 filebeat -> 카프카 -> 로그스테시 -> 엘라스틱 서치 -> 키바나 연동했습니다.
로거는 winston 사용했습니다.
#6

2024-07-01 09:30 UTC, f-lab-darwin requested changes
전체적으로 코멘트 남긴 부분 확인해 보시죠.

2024-07-01 09:30 UTC, f-lab-darwin commented on prisma/migrations/20240622083744_init/migration.sql
> +    `agreeWithMarketing` BOOLEAN NOT NULL,
이런 것들은 Default를 false로 두거나, NOT NULL이 아니거나 하는 것이 맞을 것 같네요. 실제 서비스를 만들때 이런 것들을 기본적으로 어떻게 두느냐에 따라 할일들이 많이 달라지기도 하니 참고하세요.

2024-07-01 09:30 UTC, f-lab-darwin commented on src/core/middleware/ExceptionsHandler.ts
> +        }),
JSON.stringify 실행시 exception이 발생할 수 있으니, JSON.parse와 더불어 항상 try/catch 처리를 하도록 하시죠

2024-07-01 09:30 UTC, f-lab-darwin commented on src/core/middleware/ExceptionsHandler.ts
> +      });
위에서는 JSON.stringify를 했는데, 여기서는 하지 않은 이유가 있나요?

2024-07-01 09:30 UTC, f-lab-darwin commented on src/core/page.ts
> +    this.totalPage = Math.ceil(totalCount / (pageRequest.size || 20));
pageRequest.size를 앞에서도 사용하기에, constructor 처음에 const pageRequestSize = Number(pageRequest.size)와 같이 선언해 두고, 같이 사용하는 것이 좋겠네요.
그리고 20과 같은 것은 const 로 미리 명시적인 의미를 가지는 것으로 선언해 두고 사용하면 의미 파악이 명확해서 좋아요.

2024-07-01 09:30 UTC, f-lab-darwin commented on src/core/page.ts
> +    this.existsNextPage = this.totalPage > (pageRequest.page || 1);
pageRequest.page도 Number로 변환이 필요한지 확인이 필요하고, 1 역시 const로 미리 의미를 가지는 것으로 선언해 두면 좋습니다.

2024-07-01 09:30 UTC, f-lab-darwin commented on src/core/page.ts
> +    return ((this.page || 1) - 1) * (this.size || 20);
여기에 1과 20을 미리 선언해둔 것으로 같이 사용하면 명확하겠네요.

2024-07-01 09:30 UTC, f-lab-darwin commented on src/core/swagger/page-response.dto copy.ts
> +}
이 파일은 copy는 뭔가요? 불필요한 파일인 듯?

2024-07-01 09:30 UTC, f-lab-darwin commented on src/domains/walks_board/repositories/walks-board.repository.ts
> +  async getBoard(warlsBoardIdx: number) {
오타 warlsBoardIdx => walksBoardIdx ?

2024-07-01 09:30 UTC, f-lab-darwin commented on src/domains/walks_board/repositories/walks-board.repository.ts
> +        throw new Error(`게시글을 찾을 수 없습니다: ${warlsBoardIdx}`);
이렇게 throw를 하면 404 NOT FOUND로 처리되나요?

2024-07-01 09:30 UTC, f-lab-darwin commented on src/domains/walks_board/repositories/walks-board.repository.ts
> +      return boards; // 조회된 walks_board 리스트 반환
board에 하나도 없을때 boards가 null로 내려가는지, empty list [] 로 내려가는지 등 확인이 필요하고, return value에 대한 Type을 명시하도록 하시죠.

2024-07-01 09:30 UTC, f-lab-darwin commented on src/domains/walks_board/walks-board.controller.ts
> +import { PageRequest } from 'src/core/page';
user code를 import할때 src로 시작하는 것들과 . 을 사용하는 상대경로를 사용하는 것들을 섞어서 사용하지 않도록 하시죠.

2024-07-01 09:30 UTC, f-lab-darwin commented on src/domains/walks_board/walks-board.controller.ts
> +      return res.status(200).send({
200을 숫자를 그냥 사용하는것보다 statusCode로 정의되어 있는 것을 활용하는 것이 좋고, post에 따른 create의 경우에는 주로 201을 사용하니 확인해 보시죠.

2024-07-01 09:30 UTC, f-lab-darwin commented on src/domains/walks_board/walks-board.controller.ts
> +    );
logging/monitoring을 위해서 console.log를 사용하지 않고, file로 저장되도록 하시죠. 테스트 목적이었다면, commit에는 넣지 않도록 하시고.

2024-07-01 09:30 UTC, f-lab-darwin commented on src/domains/walks_board/walks-board.controller.ts
> +    const board = await this.boardService.findWalksBoard(warlsBoardIdx);
해당 board가 없을 경우에 대한 처리가 어떻게 되는지 확인해 보시죠.

2024-07-07 08:51 UTC, wngh4628 commented on src/core/middleware/ExceptionsHandler.ts
> +        }),
수정했습니다.

2024-07-07 08:51 UTC, wngh4628 commented on src/core/middleware/ExceptionsHandler.ts
> +      });
깜빡한거 같습니다. 수정했습니다.

2024-07-07 08:57 UTC, wngh4628 commented on src/core/page.ts
> +    this.totalPage = Math.ceil(totalCount / (pageRequest.size || 20));
수정했습니다.

2024-07-07 08:59 UTC, wngh4628 commented on src/core/page.ts
> +    this.existsNextPage = this.totalPage > (pageRequest.page || 1);
수정했습니다.

2024-07-07 09:03 UTC, wngh4628 commented on src/domains/walks_board/repositories/walks-board.repository.ts
> +      return boards; // 조회된 walks_board 리스트 반환
board에 하나도 없을때에는 
{
  "boards": []
} 가 내려갑니다.
return value에 대한 Type을 Promise<walks_board[]>로 추가했습니다.

2024-07-07 09:12 UTC, wngh4628 commented on src/domains/walks_board/walks-board.controller.ts
> +import { PageRequest } from 'src/core/page';
수정했습니다.

2024-07-07 09:13 UTC, wngh4628 commented on src/domains/walks_board/walks-board.controller.ts
> +    );
수정했습니다.

2024-07-07 09:24 UTC, wngh4628 commented on src/domains/walks_board/walks-board.controller.ts
> +      return res.status(200).send({
수정했습니다.

2024-07-07 09:31 UTC, wngh4628 commented on src/domains/walks_board/walks-board.controller.ts
> +    const board = await this.boardService.findWalksBoard(warlsBoardIdx);
board가 없으면 
 if (!board) {
     throw new Error(`Board not found.`);
}
처리했습니다.

2024-07-08 09:07 UTC, f-lab-darwin commented
전체 코멘트가 처리되진 않은 것 같네요. 그리고 수정한 내역도 반영이 안 된 것 같으니 확인해 보시죠.

2024-07-22 06:05 UTC, f-lab-darwin approved these changes
다른 곳에서 수정한 것들이 있는 것 같아서 우선 승인. 머지하고 진행하시죠.

2024-07-23 09:02 UTC, merged